### ISSUE TITLE
Appnexus is returning null pointer exception while running /openrtb2/auction request

### ISSUE THREAD

**Issue by rubypt1** [rubicon-project/prebid-server-java#343]
I have tried using the appnexus request for openrtb2/auction but it is returning  the following error,

> Critical error while running the auction
> 
> java.lang.NullPointerException:

The following is my sample request:
`{
    "id": 190,
    "cur": ["USD"],
    "imp": [{
        "id": 190,
        "video": {
            "mimes": ["video/x-ms-wmv", "video/mp4"],
            "skipmin": 0,
            "skipafter": 0
        },
        "ext": {
            "appnexus": {
                "placementId": 1234
            }
        }
    }],
    "user": {
        "id": "456789876567897654678987656789",
        "buyeruid": "545678765467876567898765678987654",
        "data": [{
            "id": "6",
            "name": "Data Provider 1",
            "segment": [{
                    "id": "12341318394918",
                    "name": "auto intenders"
                },
                {
                    "id": "1234131839491234",
                    "name": "auto enthusiasts"
                }
            ]
        }]
    },
    "app": {
        "publisher": {
            "id": 1001,
            "ext": {
                "rp": {
                    "account_id": 2001
                }
            }
        },
        "ext": {
            "rp": {
                "site_id": 3001
            }
        }
    }
}`

Also, from the code I found that the usersyncer is returning null from the AppnexusConfiguration.class,

`BidderDeps(name=appnexus, deprecatedNames=[], aliases=[districtm], bidderInfo=BidderInfo(enabled=false, maintainer=BidderInfo.MaintainerInfo(email=info@prebid.org), capabilities=BidderInfo.CapabilitiesInfo(app=BidderInfo.PlatformInfo(mediaTypes=[banner, native]), site=BidderInfo.PlatformInfo(mediaTypes=[banner, video])), vendors=[], gdpr=BidderInfo.GdprInfo(vendorId=32, enforced=true)), usersyncer=null, bidder=org.prebid.server.bidder.DisabledBidder@26ceffa8, adapter=org.prebid.server.bidder.DisabledAdapter@600b90df)`

Kindly help me resolve this issue to pass this request

**Comment by RossGoncharuk** [comment]
We've started the server with the default configuration (except enabled appnexus bidder) and made the same request to openrtb2/auction endpoint and didn't get any errors (no NPE).

It seems like the issue is caused by your local settings and configurations.

Please provide the configuration file and a command you're using to start up the server as well as any other request details, such as headers.

**Comment by rpanchyk** [comment]
Also, can you please provide full stack trace error from logs. It’ll help us a lot.

**Comment by rubypt1** [comment]
> Also, can you please provide full stack trace error from logs. It’ll help us a lot.
The following is the full stack trace from error logs,
```
Critical error while running the auction

java.lang.NullPointerException: null
	at org.prebid.server.auction.ExchangeService.updateRequestMetric(ExchangeService.java:591)
	at org.prebid.server.auction.ExchangeService.lambda$holdAuction$0(ExchangeService.java:166)
	at io.vertx.core.Future.lambda$map$2(Future.java:301)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.Future.map(Future.java:297)
	at org.prebid.server.auction.ExchangeService.holdAuction(ExchangeService.java:165)
	at org.prebid.server.handler.openrtb2.AuctionHandler.lambda$handle$4(AuctionHandler.java:84)
	at io.vertx.core.Future.lambda$compose$1(Future.java:265)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
	at io.vertx.core.Future.compose(Future.java:261)
	at org.prebid.server.handler.openrtb2.AuctionHandler.handle(AuctionHandler.java:83)
	at org.prebid.server.handler.openrtb2.AuctionHandler.handle(AuctionHandler.java:37)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:147)
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:38)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at org.prebid.server.handler.NoCacheHandler.handle(NoCacheHandler.java:19)
	at org.prebid.server.handler.NoCacheHandler.handle(NoCacheHandler.java:7)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.doEnd(HttpServerRequestImpl.java:523)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:512)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:168)
	at io.vertx.core.http.impl.Http1xServerConnection.handleContent(Http1xServerConnection.java:158)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:139)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:386)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rubypt1** [comment]
@RossGoncharuk The configuration files have no changes, it contains only the values provided by the project

The following command is used to run the project,
```
mvn clean package
java -Dlogging.config=src/main/resources/logback-spring.xml -jar target/prebid-server.jar --spring.config.additional-location=sample/prebid-config.yaml
```

**Comment by RossGoncharuk** [comment]
@rubypt1 you need to enable the bidder in configurations - add the following property either to `sample/prebid-config.yaml` or `application.yaml`:

```yaml
adapters:
  appnexus:
    enabled: true
```

Also, we will fix this NPE to return a proper and more informative response if the bidder is disabled.

**Comment by RossGoncharuk** [comment]
Will be fixed in https://github.com/rubicon-project/prebid-server-java/pull/344
